# Generated by Django 4.2.3 on 2023-09-03 17:32

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='brand',
            field=models.CharField(choices=[('bmw', 'BMW'), ('mercedes_benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche'), ('mustang', 'Mustang')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='lists',
            name='color',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='lists',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='lists',
            name='engine',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='lists',
            name='image',
            field=models.ImageField(default=None, upload_to=main.utils.user_listing_path),
        ),
        migrations.AddField(
            model_name='lists',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='lists',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lists',
            name='model',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='lists',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='lists',
            name='vin',
            field=models.CharField(default=None, max_length=17),
        ),
    ]
