# Generated by Django 4.2.3 on 2023-09-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo'),
        ('main', '0004_alter_listing_brand_likedlistings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedListings',
            new_name='LikedListing',
        ),
    ]
